//*****************************************************************************
//*****************************************************************************
//  FILENAME: Timer3.h
//   Version: 2.6, Updated on 2015/3/4 at 22:27:47
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Timer16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Timer3_INCLUDE
#define Timer3_INCLUDE

#include <m8c.h>

#pragma fastcall16 Timer3_EnableInt
#pragma fastcall16 Timer3_DisableInt
#pragma fastcall16 Timer3_Start
#pragma fastcall16 Timer3_Stop
#pragma fastcall16 Timer3_wReadTimer                // Read  DR0
#pragma fastcall16 Timer3_wReadTimerSaveCV          // Read  DR0      
#pragma fastcall16 Timer3_WritePeriod               // Write DR1
#pragma fastcall16 Timer3_wReadCompareValue         // Read  DR2
#pragma fastcall16 Timer3_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wTimer3_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 wTimer3_CaptureCounter           // Read  DR0 "Obsolete"
#pragma fastcall16 wTimer3_ReadTimer                // Read  DR0 (Deprecated)
#pragma fastcall16 wTimer3_ReadTimerSaveCV          // Read  DR0 (Deprecated)
#pragma fastcall16 wTimer3_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Timer3 API.
//-------------------------------------------------

extern void Timer3_EnableInt(void);                           // Proxy 1
extern void Timer3_DisableInt(void);                          // Proxy 1
extern void Timer3_Start(void);                               // Proxy 1
extern void Timer3_Stop(void);                                // Proxy 1
extern WORD Timer3_wReadTimer(void);                          // Proxy 1
extern WORD Timer3_wReadTimerSaveCV(void);                    // Proxy 2
extern void Timer3_WritePeriod(WORD wPeriod);                 // Proxy 1
extern WORD Timer3_wReadCompareValue(void);                   // Proxy 1
extern void Timer3_WriteCompareValue(WORD wCompareValue);     // Proxy 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wTimer3_ReadCompareValue(void);       // Deprecated
extern WORD wTimer3_ReadTimerSaveCV(void);        // Deprecated
extern WORD wTimer3_ReadCounter(void);            // Obsolete
extern WORD wTimer3_ReadTimer(void);              // Deprecated
extern WORD wTimer3_CaptureCounter(void);         // Obsolete


//--------------------------------------------------
// Constants for Timer3 API's.
//--------------------------------------------------

#define Timer3_CONTROL_REG_START_BIT           ( 0x01 )
#define Timer3_INT_REG_ADDR                    ( 0x0e1 )
#define Timer3_INT_MASK                        ( 0x20 )


//--------------------------------------------------
// Constants for Timer3 user defined values
//--------------------------------------------------

#define Timer3_PERIOD                          ( 0xffff )
#define Timer3_COMPARE_VALUE                   ( 0x0 )


//-------------------------------------------------
// Register Addresses for Timer3
//-------------------------------------------------

#pragma ioport  Timer3_COUNTER_LSB_REG: 0x030              //Count register LSB
BYTE            Timer3_COUNTER_LSB_REG;
#pragma ioport  Timer3_COUNTER_MSB_REG: 0x034              //Count register MSB
BYTE            Timer3_COUNTER_MSB_REG;
#pragma ioport  Timer3_PERIOD_LSB_REG:  0x031              //Period register LSB
BYTE            Timer3_PERIOD_LSB_REG;
#pragma ioport  Timer3_PERIOD_MSB_REG:  0x035              //Period register MSB
BYTE            Timer3_PERIOD_MSB_REG;
#pragma ioport  Timer3_COMPARE_LSB_REG: 0x032              //Compare register LSB
BYTE            Timer3_COMPARE_LSB_REG;
#pragma ioport  Timer3_COMPARE_MSB_REG: 0x036              //Compare register MSB
BYTE            Timer3_COMPARE_MSB_REG;
#pragma ioport  Timer3_CONTROL_LSB_REG: 0x033              //Control register LSB
BYTE            Timer3_CONTROL_LSB_REG;
#pragma ioport  Timer3_CONTROL_MSB_REG: 0x037              //Control register MSB
BYTE            Timer3_CONTROL_MSB_REG;
#pragma ioport  Timer3_FUNC_LSB_REG:    0x130              //Function register LSB
BYTE            Timer3_FUNC_LSB_REG;
#pragma ioport  Timer3_FUNC_MSB_REG:    0x134              //Function register MSB
BYTE            Timer3_FUNC_MSB_REG;
#pragma ioport  Timer3_INPUT_LSB_REG:   0x131              //Input register LSB
BYTE            Timer3_INPUT_LSB_REG;
#pragma ioport  Timer3_INPUT_MSB_REG:   0x135              //Input register MSB
BYTE            Timer3_INPUT_MSB_REG;
#pragma ioport  Timer3_OUTPUT_LSB_REG:  0x132              //Output register LSB
BYTE            Timer3_OUTPUT_LSB_REG;
#pragma ioport  Timer3_OUTPUT_MSB_REG:  0x136              //Output register MSB
BYTE            Timer3_OUTPUT_MSB_REG;
#pragma ioport  Timer3_INT_REG:       0x0e1                //Interrupt Mask Register
BYTE            Timer3_INT_REG;


//-------------------------------------------------
// Timer3 Macro 'Functions'
//-------------------------------------------------

#define Timer3_Start_M \
   ( Timer3_CONTROL_LSB_REG |=  Timer3_CONTROL_REG_START_BIT )

#define Timer3_Stop_M  \
   ( Timer3_CONTROL_LSB_REG &= ~Timer3_CONTROL_REG_START_BIT )

#define Timer3_EnableInt_M   \
   M8C_EnableIntMask(  Timer3_INT_REG, Timer3_INT_MASK )

#define Timer3_DisableInt_M  \
   M8C_DisableIntMask( Timer3_INT_REG, Timer3_INT_MASK )

#endif
// end of file Timer3.h
