//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWM2.h
//   Version: 2.5, Updated on 2015/3/4 at 22:26:51
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: PWM16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PWM2_INCLUDE
#define PWM2_INCLUDE

#include <m8c.h>

#pragma fastcall16 PWM2_EnableInt
#pragma fastcall16 PWM2_DisableInt
#pragma fastcall16 PWM2_Start
#pragma fastcall16 PWM2_Stop
#pragma fastcall16 PWM2_wReadCounter              // Read  DR0
#pragma fastcall16 PWM2_WritePeriod               // Write DR1
#pragma fastcall16 PWM2_wReadPulseWidth           // Read  DR2
#pragma fastcall16 PWM2_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wPWM2_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wPWM2_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PWM2 API.
//-------------------------------------------------

extern void PWM2_EnableInt(void);                  // Proxy Class 1
extern void PWM2_DisableInt(void);                 // Proxy Class 1
extern void PWM2_Start(void);                      // Proxy Class 1
extern void PWM2_Stop(void);                       // Proxy Class 1
extern WORD PWM2_wReadCounter(void);               // Proxy Class 2
extern void PWM2_WritePeriod(WORD wPeriod);        // Proxy Class 1
extern WORD PWM2_wReadPulseWidth(void);            // Proxy Class 1
extern void PWM2_WritePulseWidth(WORD wPulseWidth);// Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wPWM2_ReadCounter(void);            // Deprecated
extern WORD wPWM2_ReadPulseWidth(void);         // Deprecated


//-------------------------------------------------
// Constants for PWM2 API's.
//-------------------------------------------------

#define PWM2_CONTROL_REG_START_BIT             ( 0x01 )
#define PWM2_INT_REG_ADDR                      ( 0x0df )
#define PWM2_INT_MASK                          ( 0x08 )


//--------------------------------------------------
// Constants for PWM2 user defined values
//--------------------------------------------------

#define PWM2_PERIOD                            ( 0x3e7 )
#define PWM2_PULSE_WIDTH                       ( 0x0 )


//-------------------------------------------------
// Register Addresses for PWM2
//-------------------------------------------------

#pragma ioport  PWM2_COUNTER_LSB_REG:   0x048              //DR0 Count register LSB
BYTE            PWM2_COUNTER_LSB_REG;
#pragma ioport  PWM2_COUNTER_MSB_REG:   0x04c              //DR0 Count register MSB
BYTE            PWM2_COUNTER_MSB_REG;
#pragma ioport  PWM2_PERIOD_LSB_REG:    0x049              //DR1 Period register LSB
BYTE            PWM2_PERIOD_LSB_REG;
#pragma ioport  PWM2_PERIOD_MSB_REG:    0x04d              //DR1 Period register MSB
BYTE            PWM2_PERIOD_MSB_REG;
#pragma ioport  PWM2_COMPARE_LSB_REG:   0x04a              //DR2 Compare register LSB
BYTE            PWM2_COMPARE_LSB_REG;
#pragma ioport  PWM2_COMPARE_MSB_REG:   0x04e              //DR2 Compare register MSB
BYTE            PWM2_COMPARE_MSB_REG;
#pragma ioport  PWM2_CONTROL_LSB_REG:   0x04b              //Control register LSB
BYTE            PWM2_CONTROL_LSB_REG;
#pragma ioport  PWM2_CONTROL_MSB_REG:   0x04f              //Control register MSB
BYTE            PWM2_CONTROL_MSB_REG;
#pragma ioport  PWM2_FUNC_LSB_REG:  0x148                  //Function register LSB
BYTE            PWM2_FUNC_LSB_REG;
#pragma ioport  PWM2_FUNC_MSB_REG:  0x14c                  //Function register MSB
BYTE            PWM2_FUNC_MSB_REG;
#pragma ioport  PWM2_INPUT_LSB_REG: 0x149                  //Input register LSB
BYTE            PWM2_INPUT_LSB_REG;
#pragma ioport  PWM2_INPUT_MSB_REG: 0x14d                  //Input register MSB
BYTE            PWM2_INPUT_MSB_REG;
#pragma ioport  PWM2_OUTPUT_LSB_REG:    0x14a              //Output register LSB
BYTE            PWM2_OUTPUT_LSB_REG;
#pragma ioport  PWM2_OUTPUT_MSB_REG:    0x14e              //Output register MSB
BYTE            PWM2_OUTPUT_MSB_REG;
#pragma ioport  PWM2_INT_REG:       0x0df                  //Interrupt Mask Register
BYTE            PWM2_INT_REG;


//-------------------------------------------------
// PWM2 Macro 'Functions'
//-------------------------------------------------

#define PWM2_Start_M \
   ( PWM2_CONTROL_LSB_REG |=  PWM2_CONTROL_REG_START_BIT )

#define PWM2_Stop_M  \
   ( PWM2_CONTROL_LSB_REG &= ~PWM2_CONTROL_REG_START_BIT )

#define PWM2_EnableInt_M   \
   M8C_EnableIntMask(  PWM2_INT_REG, PWM2_INT_MASK )

#define PWM2_DisableInt_M  \
   M8C_DisableIntMask( PWM2_INT_REG, PWM2_INT_MASK )

#endif
// end of file PWM2.h
