//*****************************************************************************
//*****************************************************************************
//  FILENAME: Timer1.h
//   Version: 2.6, Updated on 2015/3/4 at 22:27:47
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Timer16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Timer1_INCLUDE
#define Timer1_INCLUDE

#include <m8c.h>

#pragma fastcall16 Timer1_EnableInt
#pragma fastcall16 Timer1_DisableInt
#pragma fastcall16 Timer1_Start
#pragma fastcall16 Timer1_Stop
#pragma fastcall16 Timer1_wReadTimer                // Read  DR0
#pragma fastcall16 Timer1_wReadTimerSaveCV          // Read  DR0      
#pragma fastcall16 Timer1_WritePeriod               // Write DR1
#pragma fastcall16 Timer1_wReadCompareValue         // Read  DR2
#pragma fastcall16 Timer1_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wTimer1_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 wTimer1_CaptureCounter           // Read  DR0 "Obsolete"
#pragma fastcall16 wTimer1_ReadTimer                // Read  DR0 (Deprecated)
#pragma fastcall16 wTimer1_ReadTimerSaveCV          // Read  DR0 (Deprecated)
#pragma fastcall16 wTimer1_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Timer1 API.
//-------------------------------------------------

extern void Timer1_EnableInt(void);                           // Proxy 1
extern void Timer1_DisableInt(void);                          // Proxy 1
extern void Timer1_Start(void);                               // Proxy 1
extern void Timer1_Stop(void);                                // Proxy 1
extern WORD Timer1_wReadTimer(void);                          // Proxy 1
extern WORD Timer1_wReadTimerSaveCV(void);                    // Proxy 2
extern void Timer1_WritePeriod(WORD wPeriod);                 // Proxy 1
extern WORD Timer1_wReadCompareValue(void);                   // Proxy 1
extern void Timer1_WriteCompareValue(WORD wCompareValue);     // Proxy 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wTimer1_ReadCompareValue(void);       // Deprecated
extern WORD wTimer1_ReadTimerSaveCV(void);        // Deprecated
extern WORD wTimer1_ReadCounter(void);            // Obsolete
extern WORD wTimer1_ReadTimer(void);              // Deprecated
extern WORD wTimer1_CaptureCounter(void);         // Obsolete


//--------------------------------------------------
// Constants for Timer1 API's.
//--------------------------------------------------

#define Timer1_CONTROL_REG_START_BIT           ( 0x01 )
#define Timer1_INT_REG_ADDR                    ( 0x0e1 )
#define Timer1_INT_MASK                        ( 0x02 )


//--------------------------------------------------
// Constants for Timer1 user defined values
//--------------------------------------------------

#define Timer1_PERIOD                          ( 0xffff )
#define Timer1_COMPARE_VALUE                   ( 0x0 )


//-------------------------------------------------
// Register Addresses for Timer1
//-------------------------------------------------

#pragma ioport  Timer1_COUNTER_LSB_REG: 0x020              //Count register LSB
BYTE            Timer1_COUNTER_LSB_REG;
#pragma ioport  Timer1_COUNTER_MSB_REG: 0x024              //Count register MSB
BYTE            Timer1_COUNTER_MSB_REG;
#pragma ioport  Timer1_PERIOD_LSB_REG:  0x021              //Period register LSB
BYTE            Timer1_PERIOD_LSB_REG;
#pragma ioport  Timer1_PERIOD_MSB_REG:  0x025              //Period register MSB
BYTE            Timer1_PERIOD_MSB_REG;
#pragma ioport  Timer1_COMPARE_LSB_REG: 0x022              //Compare register LSB
BYTE            Timer1_COMPARE_LSB_REG;
#pragma ioport  Timer1_COMPARE_MSB_REG: 0x026              //Compare register MSB
BYTE            Timer1_COMPARE_MSB_REG;
#pragma ioport  Timer1_CONTROL_LSB_REG: 0x023              //Control register LSB
BYTE            Timer1_CONTROL_LSB_REG;
#pragma ioport  Timer1_CONTROL_MSB_REG: 0x027              //Control register MSB
BYTE            Timer1_CONTROL_MSB_REG;
#pragma ioport  Timer1_FUNC_LSB_REG:    0x120              //Function register LSB
BYTE            Timer1_FUNC_LSB_REG;
#pragma ioport  Timer1_FUNC_MSB_REG:    0x124              //Function register MSB
BYTE            Timer1_FUNC_MSB_REG;
#pragma ioport  Timer1_INPUT_LSB_REG:   0x121              //Input register LSB
BYTE            Timer1_INPUT_LSB_REG;
#pragma ioport  Timer1_INPUT_MSB_REG:   0x125              //Input register MSB
BYTE            Timer1_INPUT_MSB_REG;
#pragma ioport  Timer1_OUTPUT_LSB_REG:  0x122              //Output register LSB
BYTE            Timer1_OUTPUT_LSB_REG;
#pragma ioport  Timer1_OUTPUT_MSB_REG:  0x126              //Output register MSB
BYTE            Timer1_OUTPUT_MSB_REG;
#pragma ioport  Timer1_INT_REG:       0x0e1                //Interrupt Mask Register
BYTE            Timer1_INT_REG;


//-------------------------------------------------
// Timer1 Macro 'Functions'
//-------------------------------------------------

#define Timer1_Start_M \
   ( Timer1_CONTROL_LSB_REG |=  Timer1_CONTROL_REG_START_BIT )

#define Timer1_Stop_M  \
   ( Timer1_CONTROL_LSB_REG &= ~Timer1_CONTROL_REG_START_BIT )

#define Timer1_EnableInt_M   \
   M8C_EnableIntMask(  Timer1_INT_REG, Timer1_INT_MASK )

#define Timer1_DisableInt_M  \
   M8C_DisableIntMask( Timer1_INT_REG, Timer1_INT_MASK )

#endif
// end of file Timer1.h
